import type { RecipeOrigin } from '../types';

/** How a recipe got here, in the words the UI puts on it. */
export const RECIPE_ORIGIN_LABELS: Record<RecipeOrigin, string> = {
  MANUAL: 'Added by hand',
  PARSED: 'Parsed',
  PARSED_EDITED: 'Parsed & edited',
  AI_PARSED: 'Parsed by AI',
  AI_GENERATED: 'Generated by AI',
};

/**
 * What the origin filter offers, in order. UNKNOWN is the recipes captured
 * before origins were recorded — they carry no origin at all.
 */
export const RECIPE_ORIGIN_FILTERS = [
  'MANUAL', 'PARSED', 'PARSED_EDITED', 'AI_PARSED', 'AI_GENERATED', 'UNKNOWN',
] as const;

export type RecipeOriginFilter = typeof RECIPE_ORIGIN_FILTERS[number];

export const RECIPE_ORIGIN_FILTER_LABELS: Record<RecipeOriginFilter, string> = {
  ...RECIPE_ORIGIN_LABELS,
  UNKNOWN: 'Unknown',
};
